config/routes.rb
Rails.application.routes.draw do
  # Devise
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  # Root
  root 'notes#index'

  # Resources
  resources :notes

  # Custom routes
  post 'notes/search', to: 'notes#search', as: 'search_note'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  content    :text
#  user_id    :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ApplicationRecord
  belongs_to :user
  
  validates :title, :content, presence: :true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint(8)        not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :authenticate_user!

    def index
        @note = Note.new
        filter = params[:filter]
        @notes = filter ? 
            current_user.notes.where('notes.title ILIKE ? or notes.content ILIKE ?', "%#{filter}%", "%#{filter}%").order(created_at: :desc) : 
            current_user.notes.order(created_at: :desc)
    end

    def search
        redirect_to notes_path(filter: params[:search][:filter])
    end

    def create
        redirect_to notes_path, notice: 'Note created!', alert: 'success' and return if current_user.notes.create(notes_params)
        redirect_to notes_path, notice: 'Something went wrong!', alert: 'warning'
    end

    def destroy
        note = Note.find_by_id(params[:id])
        redirect_to notes_path, notice: 'Note destroyed!', alert: 'success' and return if note.destroy
        redirect_to notes_path, notice: 'Something went wrong!', alert: 'warning'
    end

    def update
        note = Note.find_by_id(params[:id])
        redirect_to notes_path, notice: 'Note updated!', alert: 'success' and return if note.update(notes_params)
        redirect_to notes_path, notice: 'Something went wrong!', alert: 'warning'
    end

    private

    def notes_params
        params.require(:note).permit(:title, :content)
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'login'
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'login'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazing Notes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if notice
      = hidden_field_tag :notice, notice, :id => 'notice'
      = hidden_field_tag :alert, alert, :id => 'alert'
      %script{:charset => "utf-8", :type => "text/javascript"}
        popup();
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.font-white
      %span.navbar-brand Amazing Notes
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            = link_to 'My Notes', notes_path, class: 'nav-link'
          = link_to 'Log Out', destroy_user_session_path, class: 'btn btn-default font-white', method: :delete
    .notes
      = yield

app/views/layouts/login.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Amazing Notes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.login-page
    = yield

app/views/notes/index.haml
.p-4
    = simple_form_for :search, url: search_note_path, html: {class: 'form-inline d-inline'} do |f|
        = f.text_field :filter, placeholder: 'By title or content', class: 'form-control mr-2'
        = f.submit 'Search', class: 'btn btn-default'
    %i.fa.fa-plus.ml-2#new-note
.row.p-4
    .col-sm-2#note-form
        = simple_form_for @note, validate: true do |f|
            .card.bg-light.mb-3{:style => "max-width: 18rem;"}
                .card-header
                    = f.input :title, placeholder: 'Title', label: false, input_html: { class: 'new-note-input bg-transparent' }
                .card-body
                    %p.card-text 
                        = f.input :content, placeholder: 'Content', label: false, input_html: { class: 'new-note-input bg-transparent' }
                        %br
                        = f.submit 'Save', class: 'btn text-right'
    - @notes.each do |n|
        .col-sm-2.hide-note-form.d-none{id: "note-#{n.id}-form"}
            = simple_form_for n, validate: true do |f|
                .card.bg-light.mb-3{:style => "max-width: 18rem;"}
                    .card-header
                        = f.input :title, placeholder: 'Title', label: false, input_html: { class: 'new-note-input bg-transparent' }
                    .card-body
                        %p.card-text 
                            = f.input :content, placeholder: 'Content', label: false, input_html: { class: 'new-note-input bg-transparent' }
                            %br
                            = f.submit 'Save', class: 'btn text-right'
        .col-sm-2.show-note-form{id: "note-#{n.id}-information"}
            .card.bg-light.mb-3{:style => "max-width: 18rem;"}
                .card-header
                    = n.title
                    %i.fa.fa-edit{onClick: "showForm(#{n.id})"}
                    = link_to note_path(n), method: :delete, class: 'color-black' do
                        %i.fa.fa-trash
                .card-body
                    %p.card-text
                        = n.content